<?php

namespace app\components;

use yii\base\ActionFilter;

class SitemapFilter extends ActionFilter
{
    public function beforeAction($action)
    {
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function afterAction($action, $result)
    {
        Sitemap::generate();
        return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
    }
}